name: musily_installer
description: "Musily installer for Linux"
publish_to: 'none'
version: 3.1.1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  path_provider: ^2.1.2
  path: ^1.8.3
  process_run: ^0.14.2
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  window_manager: ^0.4.3
  flutter_svg: ^2.1.0
  handy_window: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app/
    - assets/icons/
